version: '1.0.0'
services:
  backend:
    build:
      context: ./backend
    image: fastapi  
    container_name: fastapi
    ports:
      - 8000:8000
  
  frontend: 
    build: 
      context: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - 80:80